import { W, H } from '../engine/core';
import manifest from './manifest.generated.json';

/** Generated by tools/prep_assets.py - never edit by hand. */
export const MANIFEST = manifest;

export const PLATES = {
  awakening: 'S01_SH01_awakening_topdown_v01_final',
  puddle: 'S01_SH02_puddle_reflection_v02_final',
  system: 'S01_SH03_system_glow_v01_final',
  meadow: 'ENV_meadow_groundlevel_v01_final',
  throw: 'S03_SH01_throw_action_v01_final',
  hero: 'S04_SH01_hero_analyse_v01_final',
} as const;
export type PlateKey = keyof typeof PLATES;

export const SPRITES = {
  weasel: 'CREA_ShadowWeasel_sprite_v01_final',
} as const;
export type SpriteKey = keyof typeof SPRITES;

export const plateInfo = (k: PlateKey) => MANIFEST.plates[PLATES[k]];
export const spriteInfo = (k: SpriteKey) => MANIFEST.sprites[SPRITES[k]];

export const PLATE_OVERSCAN = 0.04;

/**
 * Maps a point of the ORIGINAL generated image (raw pixel coords, 1344x768) to
 * layer pixels, accounting for overscan and object-fit: cover. This is what makes
 * code-driven overlays land exactly on features of the AI-generated diorama.
 */
export const plateToLayer = (k: PlateKey, rawX: number, rawY: number, ov = PLATE_OVERSCAN) => {
  const p = plateInfo(k);
  const cw = W * (1 + 2 * ov);
  const ch = H * (1 + 2 * ov);
  const aspect = p.w / p.h;
  let iw = cw;
  let ih = cw / aspect;
  if (ih < ch) {
    ih = ch;
    iw = ch * aspect;
  }
  const ox = -ov * W + (cw - iw) / 2;
  const oy = -ov * H + (ch - ih) / 2;
  return { x: ox + (rawX / p.rawW) * iw, y: oy + (rawY / p.rawH) * ih };
};

/** Feature points on the weasel sprite in normalised sprite UV (measured on the keyed sprite). */
export const WEASEL_POINTS = {
  crystal: { u: 0.0755, v: 0.622 },
  eyeNear: { u: 0.113, v: 0.697 },
  eyeFar: { u: 0.054, v: 0.688 },
  head: { u: 0.1, v: 0.68 },
  feetV: 0.96,
};
