import { W, H } from '../engine/core';
import manifest from './manifest.generated.json';

/** Generated by tools/prep_assets.py - never edit by hand. */
export const MANIFEST = manifest;

type PlateEntry = { file: string; bloom: string; w: number; h: number; rawW: number; rawH: number; crop?: number[] };
type SpriteEntry = { file: string; w: number; h: number; rawBox: number[]; rawW: number; rawH: number };

export const PLATES = {
  skyPov: 'ENV_sky_pov_v01_final',
  awakening: 'S01_SH01_awakening_topdown_v01_final',
  eyes: 'S01_SH03_eyes_ecu_v01_final',
  hilltop: 'S01_SH04_hilltop_back_v01_final',
  hands: 'S01_SH05_hands_v01_final',
  puddle: 'S01_SH02_puddle_reflection_v02_final',
  system: 'S01_SH03_system_glow_v01_final',
  meadow: 'ENV_meadow_groundlevel_v01_final',
  reach: 'S02_SH02_reach_out_v01_final',
  lunge: 'S02_SH03_weasel_lunge_v01_final',
  handStone: 'S02_SH05_hand_stone_v01_final',
  throw: 'S03_SH01_throw_action_v01_final',
  hero: 'S04_SH01_hero_analyse_v01_final',
  tracks: 'S05_SH01_goblin_tracks_v01_final',
  road: 'ENV_forest_road_v01_final',
  roadNoSpear: 'ENV_forest_road_nospear_v01_final',
  threatened: 'S05_SH03_elara_threatened_v01_final',
  bushes: 'S05_SH04_kaelan_bushes_v01_final',
  thrust: 'S06_SH02_spear_thrust_v01_final',
  dodge: 'S06_SH03_dodge_v02_final',
  levelup: 'S06_SH04_levelup_v01_final',
  thanks: 'S07_SH01_elara_thanks_v01_final',
  walking: 'S07_SH02_walking_together_v01_final',
} as const;
export type PlateKey = keyof typeof PLATES;

export const SPRITES = {
  weasel: 'CREA_ShadowWeasel_sprite_v01_final',
  weaselCute: 'CREA_ShadowWeasel_cute_v01_final',
  goblinA: 'CREA_Goblin_pair_sprite_v01_final_A',
  goblinB: 'CREA_Goblin_pair_sprite_v01_final_B',
} as const;
export type SpriteKey = keyof typeof SPRITES;

export const plateInfo = (k: PlateKey): PlateEntry => (MANIFEST.plates as Record<string, PlateEntry>)[PLATES[k]];
export const spriteInfo = (k: SpriteKey): SpriteEntry => (MANIFEST.sprites as Record<string, SpriteEntry>)[SPRITES[k]];

export const PLATE_OVERSCAN = 0.04;

/**
 * Maps a point of the ORIGINAL generated image (raw pixel coords, 1344x768) to
 * layer pixels, accounting for letterbox crops, overscan and object-fit: cover.
 * This is what makes code-driven overlays land exactly on features of the
 * AI-generated diorama.
 */
export const plateToLayer = (k: PlateKey, rawX: number, rawY: number, ov = PLATE_OVERSCAN) => {
  const p = plateInfo(k);
  const [cx0, cy0, cx1, cy1] = p.crop ?? [0, 0, p.rawW, p.rawH];
  const u = (rawX - cx0) / (cx1 - cx0);
  const v = (rawY - cy0) / (cy1 - cy0);
  const cw = W * (1 + 2 * ov);
  const ch = H * (1 + 2 * ov);
  const aspect = p.w / p.h;
  let iw = cw;
  let ih = cw / aspect;
  if (ih < ch) {
    ih = ch;
    iw = ch * aspect;
  }
  const ox = -ov * W + (cw - iw) / 2;
  const oy = -ov * H + (ch - ih) / 2;
  return { x: ox + u * iw, y: oy + v * ih };
};

/** Converts a point measured on the raw generation into the keyed sprite's UV. */
export const spriteUV = (k: SpriteKey, rawX: number, rawY: number) => {
  const s = spriteInfo(k);
  const [x0, y0, x1, y1] = s.rawBox;
  return { u: (rawX - x0) / (x1 - x0), v: (rawY - y0) / (y1 - y0) };
};

/** Feature points on the weasel sprite in normalised sprite UV (measured on the keyed sprite). */
export const WEASEL_POINTS = {
  crystal: { u: 0.0755, v: 0.622 },
  eyeNear: { u: 0.113, v: 0.697 },
  eyeFar: { u: 0.054, v: 0.688 },
  head: { u: 0.1, v: 0.68 },
  feetV: 0.96,
};
